sonar.projectKey=tankwar

sonar.projectName=Tankwar C++ Project

sonar.projectVersion=1.0

sonar.sources=.

sonar.inclusions=**/*.cpp,**/*.h

sonar.sourceEncoding=UTF-8

sonar.cxx.cppcheck.reportPath=cppcheck-report.xml

sonar.host.url=http://localhost:9000
