sonar.projectKey=tankwar

sonar.projectName=Tankwar C++ Project

sonar.projectVersion=1.0

sonar.sources=client,server

sonar.inclusions=**/*.cpp,**/*.h

sonar.sourceEncoding=UTF-8

sonar.cxx.cppcheck.reportPath=cppcheck-report.xml

sonar.cxx.clangtidy.reportPaths=clang-tidy.txt

sonar.cxx.clangtidy.encoding=UTF-8

sonar.host.url=http://localhost:9000